#8761 default eureka server port
server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false #tells eureka that this is not a client (by default it will consider itself a service)
    fetch-registry: false 
  server:
    wait-time-in-ms-when-sync-empty: 0  
  instance:
    hostname: localhost