
server:
  port: 8086
 
 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: DeepGar2812#*
    url: jdbc:mysql://localhost:3306/animecollection
  jpa:
    hibernate:
      ddl-auto: update

#Configure the name of spring app
  application:
    name: Cart_Service

#Configure the eureka client
eureka:
  client:
    register-with-eureka: true #Register this with eureks
    
  instance:
    hostname: locahost